In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# read the dataset
data = pd.read_csv('Datasets/Datasets/clean_data.csv')
data.head(3)

Unnamed: 0     budget                                             genres  \
0           0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1           1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2           2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

       id                                           keywords  \
0   19995  [{"id": 1463, "name": "culture clash"}, {"id":...   
1     285  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   
2  206647  [{"id": 470, "name": "spy"}, {"id": 818, "name...   

  original_language                            original_title  \
0                en                                    Avatar   
1                en  Pirates of the Caribbean: At World's End   
2                en                                   Spectre   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   

                                production_companies release_date     revenue  \
0  [{"name": "Ingenious Film Partners", "id": 289...   2009-12-10  2787965087   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   2007-05-19   961000000   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   2015-10-26   880674609   

   runtime                                   spoken_languages  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...   
1    169.0           [{"iso_639_1": "en", "name": "English"}]   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...   

                                          tagline  vote_average  vote_count  \
0                     Enter the World of Pandora.           7.2       11800   
1  At the end of the world, the adventure begins.           6.9        4500   
2                           A Plan No One Escapes           6.3        4466   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...

In [ ]:
data.info()

In [ ]:
data.dtypes

In [3]:
data['overview']

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bond’s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...                        
4798    El Mariachi just wants to play his guitar and ...
4799    A newlywed couple's honeymoon is upended by th...
4800    "Signed, Sealed, Delivered" introduces a dedic...
4801    When ambitious New York attorney Sam is sent t...
4802    Ever since the second grade when he first saw ...
Name: overview, Length: 4803, dtype: object

In [4]:
data['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [ ]:
# finding any missing value in the overview feature
data['overview'].isnull().sum()

In [5]:
# Removing the missing values from overview column ------------
data['overview'] = data['overview'].fillna('')

In [6]:
# applying TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer

In [7]:
tfv = TfidfVectorizer(min_df=3, max_features=None, ngram_range=(1,3), stop_words='english')

In [8]:
tfv_matrix = tfv.fit_transform(data['overview'])

In [9]:
# we will get a sparse matrix
tfv_matrix

<4803x9919 sparse matrix of type '<class 'numpy.float64'>'
	with 121480 stored elements in Compressed Sparse Row format>

In [10]:
tfv_matrix.shape

(4803, 9919)

In [11]:
data['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [12]:
# Having a look at the vector representation of first movie overview
tfv_matrix.toarray()[0]

array([0., 0., 0., ..., 0., 0., 0.])

In [13]:
# Taking transpose of first review
tfv_matrix[0].T.toarray()

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [14]:
# saving the whole matrix in X
X = tfv_matrix.toarray()

In [15]:
pd.DataFrame(X)

0     1     2     3     4     5     6     7     8     9     ...  9909  \
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
1      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
4798   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4799   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4800   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4801   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4802   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

      9910  9911  9912  9913  9914  9915  9916  9917  9918  
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
4798   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4799   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4800   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4801   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4802   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[4803 rows x 9919 columns]

In [16]:
df2 = pd.DataFrame(X)

In [17]:
data['overview']

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bond’s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...                        
4798    El Mariachi just wants to play his guitar and ...
4799    A newlywed couple's honeymoon is upended by th...
4800    "Signed, Sealed, Delivered" introduces a dedic...
4801    When ambitious New York attorney Sam is sent t...
4802    Ever since the second grade when he first saw ...
Name: overview, Length: 4803, dtype: object

In [18]:
# applying sigmoid 
from sklearn.metrics.pairwise import sigmoid_kernel

In [23]:
sig = sigmoid_kernel(tfv_matrix, tfv_matrix)

In [24]:
sig[0]

array([0.76163649, 0.76159416, 0.76159416, ..., 0.76159416, 0.76159416,
       0.76159416])

In [25]:
indices = data.index
indices[4802]

4802

In [26]:
title = data['original_title']

In [27]:
title[4802]

'My Date with Drew'

In [28]:
indices = pd.Series(data.index, index=data['original_title'])
indices

original_title
Avatar                                         0
Pirates of the Caribbean: At World's End       1
Spectre                                        2
The Dark Knight Rises                          3
John Carter                                    4
                                            ... 
El Mariachi                                 4798
Newlyweds                                   4799
Signed, Sealed, Delivered                   4800
Shanghai Calling                            4801
My Date with Drew                           4802
Length: 4803, dtype: int64

In [29]:
indices['Avatar']

0

In [30]:
sig[0]

array([0.76163649, 0.76159416, 0.76159416, ..., 0.76159416, 0.76159416,
       0.76159416])

In [ ]:
len(list(sig[indices['Avatar']]))

In [ ]:
list(enumerate(list(sig[indices['Avatar']])))

In [31]:
# sort the list wrt the coefficients
sigma_scores = sorted(list(enumerate(list(sig[indices['Avatar']]))), key=lambda x:x[1], reverse=True)

In [32]:
sigma_scores

[(0, 0.76163649309625),
 (1341, 0.7616030155858681),
 (634, 0.7616028561141562),
 (3604, 0.761601930611584),
 (2130, 0.7616015339622925),
 (775, 0.7616011086528326),
 (529, 0.7615996114069044),
 (151, 0.7615991171152051),
 (311, 0.7615990624497703),
 (847, 0.7615987706430224),
 (570, 0.7615986450599548),
 (942, 0.7615984376900236),
 (36, 0.761597988130195),
 (1610, 0.7615979793934843),
 (3070, 0.7615978406764746),
 (1033, 0.7615978182403835),
 (2628, 0.7615977834088159),
 (1784, 0.7615977150705628),
 (2578, 0.7615976778191441),
 (150, 0.7615976453752452),
 (3724, 0.7615975951237102),
 (1013, 0.761597590729192),
 (4211, 0.7615975631290405),
 (1213, 0.7615975380289366),
 (1345, 0.7615974549075267),
 (312, 0.7615974086679764),
 (4039, 0.7615973645677722),
 (2967, 0.7615973512232982),
 (614, 0.7615972949789032),
 (281, 0.7615972537743877),
 (174, 0.7615972462403858),
 (3493, 0.7615971922075141),
 (3624, 0.7615971821325882),
 (972, 0.7615971791001622),
 (1274, 0.7615971587672579),
 (1959, 0

In [33]:
# take top 10 scores
sigma_scores[1:11]

[(1341, 0.7616030155858681),
 (634, 0.7616028561141562),
 (3604, 0.761601930611584),
 (2130, 0.7616015339622925),
 (775, 0.7616011086528326),
 (529, 0.7615996114069044),
 (151, 0.7615991171152051),
 (311, 0.7615990624497703),
 (847, 0.7615987706430224),
 (570, 0.7615986450599548)]

In [34]:
top_ten_indices = [index[0] for index in sigma_scores[1:11]]
top_ten_indices

[1341, 634, 3604, 2130, 775, 529, 151, 311, 847, 570]

In [35]:
data['original_title'].iloc[top_ten_indices]

1341                Obitaemyy Ostrov
634                       The Matrix
3604                       Apollo 18
2130                    The American
775                        Supernova
529                 Tears of the Sun
151                          Beowulf
311     The Adventures of Pluto Nash
847                         Semi-Pro
570                           Ransom
Name: original_title, dtype: object

In [36]:
# define a function that makes recmmendation
def give_rec(title, model):
    idx = indices[title]
    model_scores = list(enumerate(list(model[indices[idx]])))
    model_scores = sorted(model_scores, key=lambda x:x[1], reverse=True)
    model_scores = model_scores[1:11]
    movie_indices = [index[0] for index in model_scores]
    return data['original_title'].iloc[movie_indices]

In [37]:
# call the function
give_rec('Avatar', sig)

/tmp/ipykernel_17445/489250770.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  model_scores = list(enumerate(list(model[indices[idx]])))


1341                Obitaemyy Ostrov
634                       The Matrix
3604                       Apollo 18
2130                    The American
775                        Supernova
529                 Tears of the Sun
151                          Beowulf
311     The Adventures of Pluto Nash
847                         Semi-Pro
570                           Ransom
Name: original_title, dtype: object

In [38]:
data.columns

Index(['Unnamed: 0', 'budget', 'genres', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'release_date', 'revenue', 'runtime', 'spoken_languages', 'tagline',
       'vote_average', 'vote_count', 'cast', 'crew'],
      dtype='object')

In [39]:
data['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"},

In [40]:
# the above data is unstructured - Thinking to make it better
eval(data['crew'][0])

[{'credit_id': '52fe48009251416c750aca23',
  'department': 'Editing',
  'gender': 0,
  'id': 1721,
  'job': 'Editor',
  'name': 'Stephen E. Rivkin'},
 {'credit_id': '539c47ecc3a36810e3001f87',
  'department': 'Art',
  'gender': 2,
  'id': 496,
  'job': 'Production Design',
  'name': 'Rick Carter'},
 {'credit_id': '54491c89c3a3680fb4001cf7',
  'department': 'Sound',
  'gender': 0,
  'id': 900,
  'job': 'Sound Designer',
  'name': 'Christopher Boyes'},
 {'credit_id': '54491cb70e0a267480001bd0',
  'department': 'Sound',
  'gender': 0,
  'id': 900,
  'job': 'Supervising Sound Editor',
  'name': 'Christopher Boyes'},
 {'credit_id': '539c4a4cc3a36810c9002101',
  'department': 'Production',
  'gender': 1,
  'id': 1262,
  'job': 'Casting',
  'name': 'Mali Finn'},
 {'credit_id': '5544ee3b925141499f0008fc',
  'department': 'Sound',
  'gender': 2,
  'id': 1729,
  'job': 'Original Music Composer',
  'name': 'James Horner'},
 {'credit_id': '52fe48009251416c750ac9c3',
  'department': 'Directing',
  

In [41]:
from ast import literal_eval

In [42]:
features = ['cast', 'crew', 'keywords', 'genres']

In [43]:
for feature in features:
    data[feature] = data[feature].apply(literal_eval)

In [44]:
data['crew'][0]

[{'credit_id': '52fe48009251416c750aca23',
  'department': 'Editing',
  'gender': 0,
  'id': 1721,
  'job': 'Editor',
  'name': 'Stephen E. Rivkin'},
 {'credit_id': '539c47ecc3a36810e3001f87',
  'department': 'Art',
  'gender': 2,
  'id': 496,
  'job': 'Production Design',
  'name': 'Rick Carter'},
 {'credit_id': '54491c89c3a3680fb4001cf7',
  'department': 'Sound',
  'gender': 0,
  'id': 900,
  'job': 'Sound Designer',
  'name': 'Christopher Boyes'},
 {'credit_id': '54491cb70e0a267480001bd0',
  'department': 'Sound',
  'gender': 0,
  'id': 900,
  'job': 'Supervising Sound Editor',
  'name': 'Christopher Boyes'},
 {'credit_id': '539c4a4cc3a36810c9002101',
  'department': 'Production',
  'gender': 1,
  'id': 1262,
  'job': 'Casting',
  'name': 'Mali Finn'},
 {'credit_id': '5544ee3b925141499f0008fc',
  'department': 'Sound',
  'gender': 2,
  'id': 1729,
  'job': 'Original Music Composer',
  'name': 'James Horner'},
 {'credit_id': '52fe48009251416c750ac9c3',
  'department': 'Directing',
  

In [45]:
data[features]

cast  \
0     [{'cast_id': 242, 'character': 'Jake Sully', '...   
1     [{'cast_id': 4, 'character': 'Captain Jack Spa...   
2     [{'cast_id': 1, 'character': 'James Bond', 'cr...   
3     [{'cast_id': 2, 'character': 'Bruce Wayne / Ba...   
4     [{'cast_id': 5, 'character': 'John Carter', 'c...   
...                                                 ...   
4798  [{'cast_id': 1, 'character': 'El Mariachi', 'c...   
4799  [{'cast_id': 1, 'character': 'Buzzy', 'credit_...   
4800  [{'cast_id': 8, 'character': 'Oliver O’Toole',...   
4801  [{'cast_id': 3, 'character': 'Sam', 'credit_id...   
4802  [{'cast_id': 3, 'character': 'Herself', 'credi...   

                                                   crew  \
0     [{'credit_id': '52fe48009251416c750aca23', 'de...   
1     [{'credit_id': '52fe4232c3a36847f800b579', 'de...   
2     [{'credit_id': '54805967c3a36829b5002c41', 'de...   
3     [{'credit_id': '52fe4781c3a36847f81398c3', 'de...   
4     [{'credit_id': '52fe479ac3a36847f813eaa3', 'de...   
...                                                 ...   
4798  [{'credit_id': '52fe44eec3a36847f80b280b', 'de...   
4799  [{'credit_id': '52fe487dc3a368484e0fb013', 'de...   
4800  [{'credit_id': '52fe4df3c3a36847f8275ecf', 'de...   
4801  [{'credit_id': '52fe4ad9c3a368484e16a36b', 'de...   
4802  [{'credit_id': '58ce021b9251415a390165d9', 'de...   

                                               keywords  \
0     [{'id': 1463, 'name': 'culture clash'}, {'id':...   
1     [{'id': 270, 'name': 'ocean'}, {'id': 726, 'na...   
2     [{'id': 470, 'name': 'spy'}, {'id': 818, 'name...   
3     [{'id': 849, 'name': 'dc comics'}, {'id': 853,...   
4     [{'id': 818, 'name': 'based on novel'}, {'id':...   
...                                                 ...   
4798  [{'id': 5616, 'name': 'united states–mexico ba...   
4799                                                 []   
4800  [{'id': 248, 'name': 'date'}, {'id': 699, 'nam...   
4801                                                 []   
4802  [{'id': 1523, 'name': 'obsession'}, {'id': 224...   

                                                 genres  
0     [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...  
1     [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...  
2     [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...  
3     [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...  
4     [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...  
...                                                 ...  
4798  [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...  
4799  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...  
4800  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...  
4801                                                 []  
4802                [{'id': 99, 'name': 'Documentary'}]  

[4803 rows x 4 columns]

In [47]:
data['crew'][0]

[{'credit_id': '52fe48009251416c750aca23',
  'department': 'Editing',
  'gender': 0,
  'id': 1721,
  'job': 'Editor',
  'name': 'Stephen E. Rivkin'},
 {'credit_id': '539c47ecc3a36810e3001f87',
  'department': 'Art',
  'gender': 2,
  'id': 496,
  'job': 'Production Design',
  'name': 'Rick Carter'},
 {'credit_id': '54491c89c3a3680fb4001cf7',
  'department': 'Sound',
  'gender': 0,
  'id': 900,
  'job': 'Sound Designer',
  'name': 'Christopher Boyes'},
 {'credit_id': '54491cb70e0a267480001bd0',
  'department': 'Sound',
  'gender': 0,
  'id': 900,
  'job': 'Supervising Sound Editor',
  'name': 'Christopher Boyes'},
 {'credit_id': '539c4a4cc3a36810c9002101',
  'department': 'Production',
  'gender': 1,
  'id': 1262,
  'job': 'Casting',
  'name': 'Mali Finn'},
 {'credit_id': '5544ee3b925141499f0008fc',
  'department': 'Sound',
  'gender': 2,
  'id': 1729,
  'job': 'Original Music Composer',
  'name': 'James Horner'},
 {'credit_id': '52fe48009251416c750ac9c3',
  'department': 'Directing',
  